### ISSUE TITLE
Disconnect Broker doesn't release connection and associate task

### ISSUE THREAD

**Issue by BDeus** [gigya/KafkaNetClient#7]
As we discuss with @Eranofer here https://github.com/EranOfer/KafkaNetClient/pull/6, there is an issue with disconnected or idle broker. The KafkaConnection doesn't release the associate tasks while topics metadata shows that this broker doesn't exist anymore.

IMHO, i think a disconnected broker should dispose the KafkaConnection because tcp read and write queues still lock tasks which have been assigned to it.

**Comment by EranOfer** [comment]
> because tcp read and write queues still lock tasks which have been assigned to it

The requests that were already passed to the `KafkaConnection` will not remain stuck, since the `TaskCompletionSource` created on the  `AsyncRequestItem` is resolved either by an exception while calling `WriteAsync` or by a task timeout. So I don't think this is an issue.

I do agree that it's wasteful that the `KafkaConnection` keeps trying to read from `KafkaTcpSocket`, even if it's not needed. This can solved by turning off the `StartReadStreamPoller` in case there are no pending tasks on that connection (and turn it on when new requests arrive), and a similar solution in `KafkaTcpSocket` (although more complex). What do you think?
